Update Product.php
woocommerce/woocommerce-square pull request #191
Opened 2024-07-29 12:10 UTC by sunile2m

Bug accessing database table with statically added "wp_" db prefix.

### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

Closes # .

### Steps to test the changes in this Pull Request:

1.
1.
1.

### Changelog entry

> Add - Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2024-07-30 14:14 UTC, dkotter requested changes

2024-07-30 14:14 UTC, dkotter commented on includes/Handlers/Product.php
> +				INNER JOIN $tablename pp ON pp.ID = pr.post_parent
I'd suggest instead of saving the table name into a new variable, we just add the prefix inline to match how we do this in other places:

```suggestion
				FROM {$wpdb->prefix}posts pr
				INNER JOIN {$wpdb->prefix}posts pp ON pp.ID = pr.post_parent
```

2024-07-30 15:20 UTC, dkotter requested changes

2024-07-30 15:20 UTC, dkotter commented on includes/Handlers/Product.php
> +		$tablename = $wpdb->prefix.'posts';
This can be removed now

2024-07-31 14:11 UTC, dkotter commented on includes/Handlers/Product.php
> +
```suggestion

```

2024-07-31 14:11 UTC, dkotter approved these changes

2024-08-05 15:05 UTC, qasumitbagthariya commented
### QA Update ✅ 

-------------

I have verified this PR in the `sunile2m:trunk` branch and functioning as intended.

I tested the following on this branch:
- Import product (simple, variable)
- Sync
- Simple product
- Subscription product / renew product

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.1.4
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Branch: sunile2m:trunk

</Details>


Steps to Test- As mentioned in the PR description.
Test Results - It is working as expected.
Functional Demo / Screencast - 
Special Notes -  Ready for code review (Woo)
Testing Document status:
Cases related to this Issue/PR are added to the Critical Flow Wiki pages: 

- [ ] Yes
- [x] Not Required/Applicable for this PR
------------------------------------------------

2024-08-15 07:42 UTC, qasumitbagthariya commented
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.5.5, npm version 8.19.4, node version 16.20.0)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.6.1
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.2
- WooCommerce - 9.1.4
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS Ventura 13.3 
- Branch: smoke-testing

</Details>



Next Step- Ready to Merge 🚀

2024-08-23 14:49 UTC, merged