fix/202: make "You're connected to Square" page entire UI to be visible
woocommerce/woocommerce-square pull request #224
Opened 2024-09-25 10:32 UTC by Sidsector9

### All Submissions:

* [ ] Does your code follow the [WooCommerce Sniffs](https://github.com/woocommerce/woocommerce-sniffs/) variant of WordPress coding standards?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully run tests with your changes locally?
* [ ] Will this change require new documentation or changes to existing documentation?

---

### Changes proposed in this Pull Request:

This PR uses combination of max/min - width/height media queries to ensure the "Next" button is always visible on the screen for desktop resolution as low as `1280 x 720`.

Closes #202

### Steps to test the changes in this Pull Request:

- Test for minimum desktop resolution of `1280 x 720`
- Test for mobile resolution.

### Changelog entry

> Fix - Vertical spacing on "Enable Payment Methods" step.

2024-09-25 15:07 UTC, dkotter requested changes

2024-09-25 15:07 UTC, dkotter commented on src/new-user-experience/components/onboarding-header/index.js
> +						window.location.href =
Looks like an eslint issue that needs cleaned up here

2024-09-25 19:16 UTC, dkotter approved these changes

2024-09-27 09:47 UTC, qasumitbagthariya commented
QA Update: ❌
---

@Sidsector9  Thanks for the PR

I cross-checked with the `fix/202` branch, and it seems like the designs for the following screens are not displaying properly:

- Select your business location
- Configure sync setting
- Manage payment method

Could you please check from your end as well?
 

https://github.com/user-attachments/assets/f9a6e332-9f57-4d80-a3eb-9eaef0f18c05

2024-10-03 12:22 UTC, qasumitbagthariya commented
QA Update: ❌
---

@Sidsector9 

Issue - 1

Unable to scroll down in 1024x768 resolution.

![image](https://github.com/user-attachments/assets/45f6de31-cef5-4daa-93cc-acd4329fc89d)

https://github.com/user-attachments/assets/0d96116f-3f26-4416-97b3-65627de38948

----
Issue - 2

In this, fix branch I notice Some screen settings are flickering while selecting.

https://github.com/user-attachments/assets/26928a70-1745-4517-8dad-429fe17eae57

2024-10-07 12:34 UTC, Sidsector9 commented
@qasumitbagthariya as discussed on Slack, the minimum supported screen size is `1200 x 900px`.

2025-04-07 11:33 UTC, qasumitbagthariya commented
QA Update: ⚠️ 
--- 

@Sidsector9 

I notice that the Next button at the bottom right corner is partially hidden and not fully visible to the user. This may affect usability, as users might struggle to scroll and proceed to the next step.

My screen resolution is 1512*982

<img width="1511" alt="image" src="https://github.com/user-attachments/assets/83be7b1c-bec7-49d6-9553-4f27f56b7dd4" />

---

I just want to confirm — have we made changes to the Manage Payment Methods UI? Because earlier it looked a bit different, with a smaller-sized button.

**Fix PR**
<img width="1487" alt="image" src="https://github.com/user-attachments/assets/06334d15-1ac6-43ac-bfec-cf0678f9ca14" />

**Before:**
<img width="927" alt="image" src="https://github.com/user-attachments/assets/13bf22e6-b805-4543-9ca5-eb509df10b3b" />

2025-08-01 13:21 UTC, jeffpaul commented
@Sidsector9 @qasumitbagthariya I think I'm fine with the current state of the updated UX here... not seeing any MAJOR issues so any concerns with us moving this along for UAT?

2025-08-06 21:08 UTC, Sidsector9 commented
@jeffpaul I'm cool with the current state as well. @qasumitbagthariya what say you?

2025-08-07 15:38 UTC, qasumitbagthariya commented
@jeffpaul yes, the current state looks good to me as well.

> @jeffpaul I'm cool with the current state as well. @qasumitbagthariya what say you?

2025-08-19 21:02 UTC, qasumitbagthariya commented
Regression / Smoke Test Report  ✅ 
-------

Tested with Archive File created via "php woorelease.phar build repo_URL" (Composer version 2.8.4, npm version 10.8.2, node version 20.18.1)

Status- Working expected with Plugin Archive/Zip file same as fix specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.8.2
- Theme: Twenty Twenty-Five 1.2
- WooCommerce - 10.1.0
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>

Next Step- Ready to Merge 🚀

2025-08-19 21:03 UTC, qasumitbagthariya approved these changes

2025-08-21 11:31 UTC, merged